### ISSUE TITLE
Опечатки 2 лекции

### ISSUE THREAD

**Issue by Kirillog** [koreshaSp/matan2#19]
1. Для чистоты, определение внешней меры слегка другое, нужно взять $E \subset \cup E_k$, $\mu^{\star}(E) \leqslant \mu^{\star}(\cup E_k)$ ( $\inf$ по меньшему множеству), а потом уже можно доказывать следующее утверждение.
![image](https://user-images.githubusercontent.com/47280521/194764352-8461d81e-443f-4c42-b6bc-8561ac0db2b8.png)
2. ( $a^{\star} - \sigma$ алгебра) $N \to \infty$
![image](https://user-images.githubusercontent.com/47280521/194769904-acf9ba57-7acc-43e2-90c9-94c6651ed0cf.png)
3. (Теорема Каратеодори) просто $\mu_0$, без звездочки и еще $\sqcup Q_{kj} = P_k \setminus P$, т. к. вообще не факт, что $E$ в полукольце ячеек
![image](https://user-images.githubusercontent.com/47280521/194773261-1ffe9bf8-28c1-426d-944e-329352df65aa.png)

**Comment by khaser** [comment]
Всё исправлено в коммите, попадёт в main, когда замёрджим последние лекции 
https://github.com/koreshaSp/matan2/commit/b15ff5b7e7ad1e3a15d0e45b8ff6912a66a7a37f
