### ISSUE TITLE
Опечатки 5-ой лекции

### ISSUE THREAD

**Issue by Kirillog** [koreshaSp/matan2#32]
1) Потерялся значок суммы в последней строчке выкладок
![image](https://user-images.githubusercontent.com/47280521/201988057-f2df7d37-eeb3-4851-9e0d-1788f2dca415.png)
2) Верно обратное
![image](https://user-images.githubusercontent.com/47280521/201989007-a61555a0-4431-448c-9836-83cb4a73da87.png)
3) Тут мы все-таки конечность интгерала $\int_X f d \mu$ требуем
![image](https://user-images.githubusercontent.com/47280521/201989822-90a79551-16b3-4aba-9e67-9e77cdc6e83a.png)
4) Где-то в док-ве должно быть $E_k$
![image](https://user-images.githubusercontent.com/47280521/202032682-4afc33ec-a7c6-450a-b138-2d496c9a8a19.png)
5) Тут TODO вписана, видимо надо вставить что-то в стиле -- по монотонности интеграла, $|\int f d \mu| \leq \int |f| d \mu \leq \int g d \mu < +\infty$, поэтому интеграл конечен
![image](https://user-images.githubusercontent.com/47280521/202038423-195076c5-a653-464a-96ba-3aa93270869a.png)
6) $\mu(F)$
![image](https://user-images.githubusercontent.com/47280521/202039768-62dee6e6-ce01-4c03-82a3-1cd26486ea43.png)
7) $\int$
![image](https://user-images.githubusercontent.com/47280521/202040886-1813651c-76d8-4e84-b2ee-1e9b438893f1.png)

**Comment by sharkov63** [comment]
Исправлены в ПР #46
