### ISSUE TITLE
Формулировка теоремы Леви

### ISSUE THREAD

**Issue by Kirillog** [koreshaSp/matan2#37]
На паре, как и в конспекте, было следующее определение:
![image](https://user-images.githubusercontent.com/47280521/202923712-2b1bafa3-d65e-41d7-ac5c-b8cc351bebd7.png)
Тем не менее, нигде в доказательстве конечность значений $f_n$ не использовалась, а в лемме Фату она применялась для измеримых неотрицательных функций, из чего я делаю вывод, что условие на простоту $f_n$ излишнее, и нужно заменить на просто измеримость. Так ли это?

**Comment by sharkov63** [comment]
Да, можно изменить ну измеримость. Более того, мы потом пользовались теоремой Леви когда функции не простые

**Comment by sharkov63** [comment]
> Да, можно изменить ну измеримость. Более того, мы потом пользовались теоремой Леви когда функции не простые

Мы использовали теорему Леви для последовательности не обязательно простых функций в утверждении о том, что $\int_E f d\mu$ - мера.

**Comment by sharkov63** [comment]
Исправлено в PR #45
