### ISSUE TITLE
Опечатки 1 лекции

### ISSUE THREAD

**Issue by Kirillog** [koreshaSp/matan2#9]
В условии потерялось \varphi
![image](https://user-images.githubusercontent.com/47280521/190501726-fc9c1cd2-2d8c-4e20-82e1-c3358115aecc.png)
Почти уверен, что тут \cap, а не \cup
![image](https://user-images.githubusercontent.com/47280521/190502038-dbf5bd06-0227-466c-a609-361b29d9830a.png)
А тут тавтология
![image](https://user-images.githubusercontent.com/47280521/190502214-082ab9b3-a523-41f0-86ba-06554756267e.png)
Во второй части нужно заменить все b_i, a_i на просто b, a, иначе мы не докажем счетную аддитивность(
![image](https://user-images.githubusercontent.com/47280521/190502402-b84dd4c3-eae7-4b5c-a9e8-4908cb07b346.png)

**Comment by sharkov63** [comment]
@Kirillog Проверь, пожалуйста, что опечатки актуальный на данный момент в main

**Comment by Kirillog** [comment]
> @Kirillog Проверь, пожалуйста, что опечатки актуальны на данный момент в main.

Все актуальны в последней сборке от [2022.10.07-07.52](https://github.com/koreshaSp/matan2/releases/tag/2022.10.07-07.52)

**Comment by khaser** [comment]
Исправил все эти опечатки и ещё некоторые, что нашёл сам в коммите https://github.com/koreshaSp/matan2/commit/b754f5150fe1cdae7a79ca743d715c6c0ffa138c
